### ISSUE TITLE
Assuming subprocess reads STDIN before writing results in deadlock

### ISSUE THREAD

**Issue by aantron** [dsheets/ocaml-process#2]
The following pair of test programs cause a deadlock due to full pipe buffers:

``` ocaml
(* subprocess.ml *)
let () =
  let megabyte = String.make (1024 * 1024) ' ' in
  print_string megabyte
```

``` ocaml
(* test.ml *)
let () =
  let megabyte = Bytes.make (1024 * 1024) ' ' in
  Process.read_stdout ~stdin:megabyte "./subprocess" [||] |> ignore
```

``` sh
ocamlfind opt -o subprocess subprocess.ml
ocamlfind opt -linkpkg -package process test.ml
./a.out
```

I think the solution is to do non-blocking writing interleaved with attempts to read in `execute`. It would also be nice to handle `SIGPIPE`.

I started writing a process helper, since Alcotest doesn't provide one, but then found `process`. I think I can use `process` as-is for my current purpose, but the code based on it would be fragile due to hidden assumptions about how the called processes do I/O.

**Comment by dsheets** [comment]
`process` is quite nascent right now and contains only enough functionality to wrap some OS X system tools like `plutil` and `hdiutil` that I've started writing. I'd really love to improve it in a number of ways and would gladly accept PRs to make it better. I will take a look at fixing the I/O assumptions you mention because deadlock should never occur.

**Comment by dsheets** [comment]
This should be fixed now. Please, let me know if there are any further issues you find.

`process` 0.2.0 should be in opam shortly (ocaml/opam-repository#5456).

**Comment by aantron** [comment]
Thanks! Nice commit. I was going to offer to write some tests using Alcotest (in part to get familiar with it), but looks like you have that covered.
